### ISSUE TITLE
"Since XXXX" should not appear if date is not available

### ISSUE THREAD

**Issue by dreisch111** [wileyprototypes/TDA#1]
For some journals, we unfortunately won't have "published since" dates. Currently, when the date is not available, the template shows "Published by Hindawi, A Wiley Brand | Since" Which looks incomplete to a user.

Can we please check to see if the publishedSince property is defined and non-empty before displaying the pipe and the word "Since"?

**Comment by jd-delatorre** [comment]
It's been updated.  Please do a hard refresh and review again.  @dreisch111
