### ISSUE TITLE
Journal title doesn't wrap properly when it is too long for one line

### ISSUE THREAD

**Issue by dreisch111** [wileyprototypes/TDA#16]
Issue:
When a journal title is long enough, it is covered by the "Start your transfer" button

Expected:
The journal title should wrap with some right-hand padding so it never touches or conflicts with the transfer button

Example:
https://wileyprototypes.github.io/TDA/email.html?userid=gabrielincoomghana@gmail.com

![image](https://user-images.githubusercontent.com/60155705/145640913-e94566bd-be2d-44be-8456-8913da5fc16f.png)

**Comment by jd-delatorre** [comment]
updated.
